// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createTimeoutFetch } from '@/lib/fetchWithTimeout';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Añadido a mano pese al aviso de arriba (el archivo ya no lo regenera
  // nadie): sin límite de tiempo, una petición colgada dejaba la app en la
  // rueda del arranque para siempre. Ver src/lib/fetchWithTimeout.ts.
  global: { fetch: createTimeoutFetch() },
});